apiVersion: v1
kind: ConfigMap
metadata:
  name: "gerrit-config"
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
data:
  # When the config map is mounted as a volume, these will be created as files.
  helloworld.sh: |
    LIBRARY_DIR=${GERRIT_SITE}/lib/
    PLUGINS_DIR=${GERRIT_SITE}/plugins/
    
    {{- range $lib := .Values.libs }}
    ls -ltr
    su-exec ${GERRIT_USER} sh -c "cd ${LIBRARY_DIR} && curl -fLO {{ $lib.url }}"
    {{- end }}
    
    echo "XXXX PLUGIN_DIR: $PLUGINS_DIR"
    echo "XXXX PWD: `pwd`"
    {{- range $plugin := .Values.plugins }}
    echo "XXXX PWD: `pwd`"
    echo "XXXX LS"
    ls -ltr 
    su-exec ${GERRIT_USER} sh -c "cd ${PLUGINS_DIR} && curl -fLO {{ $plugin.url }}"
    {{- end }}

    cd /
