apiVersion: v1
kind: Service
metadata:
  name: {{ template "gerrit.fullname" . }}-web
  labels:
    app: {{ template "gerrit.name" . }}
    chart: {{ template "gerrit.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.web.service.type }}
  ports:
    - port: {{ .Values.web.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ template "gerrit.name" . }}
    release: {{ .Release.Name }}
