{{- if .Values.volumes }}
{{- range $key, $volume := .Values.volumes }}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: "{{ $key }}"
  labels:
    app: gerrit
  annotations:
  {{- if $volume.storageClass }}
    volume.beta.kubernetes.io/storage-class: {{ $volume.storageClass | quote }}
  {{- else }}
    volume.alpha.kubernetes.io/storage-class: default
  {{- end }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ $volume.size | quote }}

{{- end }}
{{- end }}
